name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: 'practica4-infra/package-lock.json'

      - name: Install dependencies
        working-directory: ./practica4-infra
        run: npm ci

      #  Ejecuta pruebas unitarias y genera reporte de cobertura
      - name: Run unit tests and generate coverage
        working-directory: ./practica4-infra
        run: npx vitest run --coverage --coverage.provider=istanbul

      # Publica el resultado
      - name: Publish Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: practica4-infra/coverage/

      #Desplegar en producción
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'practica4-infra'
          environment: 'production' # ESTO DEFINE EL STAGE DE PRODUCCIÓN

      #Task para las UAT apuntando a Prod
      - name: Run UAT (User Acceptance Testing)
        run: |
          echo "Ejecutando prueba de aceptación del usuario en PRODUCCIÓN..."
          curl -f -s https://broken-math-b1d1-prod.callecaracol234.workers.dev/users
          echo ""
          echo "¡UAT superado! El entorno de PRODUCCIÓN responde correctamente."
