name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: 'practica4-infra/package-lock.json'

      - name: Install dependencies
        working-directory: ./practica4-infra # Entra a la carpeta
        run: npm ci

      - name: Run unit tests
        working-directory: ./practica4-infra # Entra a la carpeta
        run: npm test -- --run

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'practica4-infra'
      # Agregar una task para las UAT
      - name: Run UAT (User Acceptance Testing)
        run: |
          echo "Ejecutando prueba de aceptación del usuario..."
          echo "Haciendo petición a la URL de producción para comprobar si responde:"

          # curl -f hace que el pipeline falle si la página da error (ej. 404 o 500)
          curl -f -s https://broken-math-b1d1.callecaracol234.workers.dev/users

          echo ""
          echo "La base de datos responde correctamente en internet."
          # REQUISITO: Ejecutar pruebas unitarias y Generar el reporte de cobertura

      # Ejecutar pruebas unitarias y Generar el reporte de cobertura
      - name: Run unit tests and generate coverage
        working-directory: ./practica4-infra
        run: npx vitest run --coverage
